// Locale-aware UI labels for the patient self-service intake survey wizard.
// Follows the same pattern as calcLabels.ts in features/website/components.

import type { IntakeLang } from './types';

export const LANG_DEFAULT_COUNTRY: Record<IntakeLang, string> = {
  ko: 'KR',
  th: 'TH',
  vi: 'VN',
  en: 'US',
  'zh-hans': 'CN',
  'zh-hant': 'TW',
  ja: 'JP',
  es: 'MX',
  ar: 'SA',
};

export interface IntakeLabelSet {
  pageTitle: string;
  stepOf: (n: number, total: number) => string;
  next: string;
  prev: string;
  submit: string;
  submitting: string;
  doneTitle: string;
  doneBody: string;
  retry: string;
  required: string;
  invalidBirth: string;
  submitError: string;
  // step titles
  s1Title: string;
  s2Title: string;
  s3Title: string;
  s4Title: string;
  s5Title: string;
  s6Title: string;
  // step1 basic info
  name: string;
  nameEn: string;
  gender: string;
  male: string;
  female: string;
  birth: string;
  year: string;
  month: string;
  day: string;
  country: string;
  countrySearch: string;
  countryEmpty: string;
  growthRef: string;
  growthRefHint: string;
  fatherH: string;
  motherH: string;
  desiredH: string;
  currentH: string;
  currentW: string;
  grade: string;
  classRank: string;
  phone: string;
  email: string;
  address: string;
  // step1 birth info
  gestWeeks: string;
  birthWeight: string;
  birthNote: string;
  // step2 growth history
  growthHint: string;
  ageCol: string;
  heightCol: string;
  yearlyGrowth: string;
  flagRapid: string;
  flagSlowed: string;
  flagPuberty: string;
  // step3 family/interest (yes/no questions)
  yes: string;
  no: string;
  pastConsult: string;
  parentsInterested: string;
  sportsAthlete: string;
  sportsEvent: string;
  childInterested: string;
  // lifestyle step
  sLifeTitle: string;
  sleepTime: string;
  wakeTime: string;
  exerciseFreq: string;
  exerciseOpts: { value: string; label: string }[];
  milkDaily: string;
  milkOpts: { value: string; label: string }[];
  mealReg: string;
  mealOpts: { value: string; label: string }[];
  // step4 medical
  chronic: string;
  tanner: string;
  tannerOpts: string[]; // EXACTLY 5 entries, Tanner stage 1..5 lay-friendly descriptions
  currentMeds: string;
  // step4 puberty detail (gender-branched)
  voiceChange: string;
  voiceOpts: { value: string; label: string }[];
  facialHair: string;
  facialOpts: { value: string; label: string }[];
  menarche: string;
  menarcheOpts: { value: string; label: string }[];
  breastDev: string;
  breastOpts: { value: string; label: string }[];
  // step5 short-stature causes
  causes: string;
  causeOpts: { value: string; label: string }[];
  causesOther: string;
  additionalNotes: string;
  // step3 acquisition channel
  acquisitionChannel: string;
  acquisitionChannelOpts: { value: string; label: string }[];
  // step6 uploads
  xrayUpload: string;
  labUpload: string;
  uploadHint: string;
}

export const INTAKE_LABELS: Record<IntakeLang, IntakeLabelSet> = {
  ko: {
    pageTitle: '187 성장클리닉 사전 문진',
    stepOf: (n, t) => `${n} / ${t} 단계`,
    next: '다음',
    prev: '이전',
    submit: '제출하기',
    submitting: '제출 중...',
    doneTitle: '감사합니다',
    doneBody: '설문이 접수되었습니다. 곧 연락드리겠습니다.',
    retry: '다시 시도',
    required: '필수 항목입니다',
    invalidBirth: '생년월일이 올바르지 않습니다. 다시 확인해 주세요.',
    submitError: '제출 중 문제가 발생했습니다. 입력 내용을 확인하고 다시 시도해 주세요.',
    s1Title: '기본 정보',
    s2Title: '과거 성장표',
    s3Title: '가족 · 관심도',
    s4Title: '의료 · 발달',
    s5Title: '키가 작은 원인',
    s6Title: '검사 파일 첨부',
    name: '이름',
    nameEn: '영문 이름',
    gender: '성별',
    male: '남아',
    female: '여아',
    birth: '생년월일',
    year: '년',
    month: '월',
    day: '일',
    country: '거주 국가',
    countrySearch: '국가 검색',
    countryEmpty: '검색 결과 없음',
    growthRef: '아이의 성장 기준 국가',
    growthRefHint: '어느 나라 아이들과 비교해 예측할까요? 보통 거주 국가와 같습니다.',
    fatherH: '아버지 키 (cm)',
    motherH: '어머니 키 (cm)',
    desiredH: '희망 키 (cm)',
    currentH: '현재 키 (cm)',
    currentW: '현재 몸무게 (kg)',
    grade: '학년',
    classRank: '학급 내 키번호',
    phone: '연락처',
    email: '이메일',
    address: '거주지',
    gestWeeks: '출생 시 임신 주수 (주)',
    birthWeight: '출생 시 몸무게 (kg)',
    birthNote: '출생 시 특이사항',
    growthHint: '생활기록부 또는 소아과 기록을 참고해 입력해 주세요.',
    ageCol: '나이 (학년)',
    heightCol: '키 (cm)',
    yearlyGrowth: '최근 1년간 자란 키 (cm)',
    flagRapid: '최근 키가 부쩍 많이 자란다',
    flagSlowed: '최근 크는 속도가 급격히 줄었다',
    flagPuberty: '성조숙증이 걱정된다',
    yes: '예',
    no: '아니오',
    pastConsult: '과거 성장 클리닉에서 상담해 본 적이 있습니까?',
    parentsInterested: '양측 부모님 모두 성장 클리닉에 관심이 있으십니까?',
    sportsAthlete: '체육 특기생입니까?',
    sportsEvent: '종목',
    childInterested: '아이도 키 크는 것에 관심이 있습니까?',
    acquisitionChannel: '저희를 어떻게 알게 되셨나요?',
    acquisitionChannelOpts: [
      { value: 'google', label: '구글 검색' },
      { value: 'naver', label: '네이버 검색' },
      { value: 'instagram', label: '인스타그램' },
      { value: 'facebook', label: '페이스북' },
      { value: 'youtube', label: '유튜브' },
      { value: 'referral', label: '지인 소개' },
      { value: 'ai', label: 'ChatGPT 등 AI' },
      { value: 'other', label: '기타' },
    ],
    sLifeTitle: '생활 습관',
    sleepTime: '취침 시간',
    wakeTime: '기상 시간',
    exerciseFreq: '운동 빈도',
    exerciseOpts: [
      { value: 'none', label: '거의 안 함' },
      { value: 'week1_2', label: '주 1~2회' },
      { value: 'week3_4', label: '주 3~4회' },
      { value: 'daily', label: '매일' },
    ],
    milkDaily: '우유/유제품 섭취',
    milkOpts: [
      { value: 'none', label: '거의 안 먹음' },
      { value: 'sometimes', label: '가끔 (주 2~3회)' },
      { value: 'daily1', label: '매일 1잔' },
      { value: 'daily2plus', label: '매일 2잔 이상' },
    ],
    mealReg: '식사 규칙성',
    mealOpts: [
      { value: 'irregular', label: '불규칙' },
      { value: 'mostly_regular', label: '대체로 규칙적' },
      { value: 'very_regular', label: '매우 규칙적' },
    ],
    chronic: '과거 또는 현재 치료 중인 질환이 있다면 적어 주세요.',
    tanner: '사춘기 단계 (Tanner 단계)',
    tannerOpts: [
      '1단계 — 아직 사춘기 변화가 없음',
      '2단계 — 사춘기 변화가 막 시작됨',
      '3단계 — 사춘기 변화가 눈에 띄게 진행 중',
      '4단계 — 사춘기가 거의 완성됨',
      '5단계 — 사춘기 완료, 성인 체형',
    ],
    currentMeds: '현재 복용 중인 약/영양제',
    voiceChange: '변성기 (목소리 변화)',
    voiceOpts: [
      { value: 'none', label: '아직 없음' },
      { value: 'started', label: '시작됨' },
      { value: 'done', label: '완료됨' },
    ],
    facialHair: '수염/체모',
    facialOpts: [
      { value: 'none', label: '없음' },
      { value: 'fuzz', label: '솜털 정도' },
      { value: 'clear', label: '뚜렷하게 있음' },
    ],
    menarche: '초경 여부',
    menarcheOpts: [
      { value: 'none', label: '아직 없음' },
      { value: 'recent6m', label: '시작됨 (최근 6개월 내)' },
      { value: 'over1y', label: '1년 이상 됨' },
    ],
    breastDev: '유방 발달',
    breastOpts: [
      { value: 'none', label: '발달 전' },
      { value: 'budding', label: '봉우리 시작' },
      { value: 'clear', label: '뚜렷한 발달' },
    ],
    causes: '키가 작은 원인 (해당하는 것 모두 선택)',
    causeOpts: [
      { value: 'parents_short', label: '부모님의 키가 작다' },
      { value: 'parents_height_gap', label: '부모님의 키 차이가 크다' },
      { value: 'picky_eating', label: '편식 · 식사 부족' },
      { value: 'parents_early_stop', label: '부모님이 어렸을 때 일찍 성장이 멈췄다' },
      { value: 'insufficient_sleep', label: '수면 시간이 부족하다' },
      { value: 'chronic_illness', label: '지속 치료 중인 질환이 있다' },
    ],
    causesOther: '기타 원인',
    additionalNotes: '추가 메모 (궁금한 점, 참고사항)',
    xrayUpload: 'X-ray 파일 첨부',
    labUpload: '검사 결과지 첨부',
    uploadHint: '이미지 또는 PDF 파일을 첨부해 주세요. (선택 사항)',
  },

  th: {
    pageTitle: 'แบบสอบถามก่อนพบแพทย์ 187 Growth Clinic',
    stepOf: (n, t) => `ขั้นตอน ${n} / ${t}`,
    next: 'ถัดไป',
    prev: 'ย้อนกลับ',
    submit: 'ส่งแบบฟอร์ม',
    submitting: 'กำลังส่ง...',
    doneTitle: 'ขอบคุณครับ',
    doneBody: 'ได้รับแบบสอบถามของคุณแล้ว ทางคลินิกจะติดต่อกลับในเร็ว ๆ นี้',
    retry: 'ลองอีกครั้ง',
    required: 'กรุณากรอกข้อมูลนี้',
    invalidBirth: 'วันเกิดไม่ถูกต้อง กรุณาตรวจสอบอีกครั้ง',
    submitError: 'เกิดข้อผิดพลาดในการส่ง กรุณาตรวจสอบข้อมูลแล้วลองใหม่',
    s1Title: 'ข้อมูลพื้นฐาน',
    s2Title: 'ประวัติการเจริญเติบโต',
    s3Title: 'ครอบครัว · ความสนใจ',
    s4Title: 'ประวัติสุขภาพ · พัฒนาการ',
    s5Title: 'สาเหตุส่วนสูงน้อย',
    s6Title: 'แนบไฟล์ผลตรวจ',
    name: 'ชื่อ-นามสกุล',
    nameEn: 'ชื่อภาษาอังกฤษ',
    gender: 'เพศ',
    male: 'เด็กชาย',
    female: 'เด็กหญิง',
    birth: 'วันเกิด',
    year: 'ปี',
    month: 'เดือน',
    day: 'วัน',
    country: 'ประเทศที่อาศัยอยู่',
    countrySearch: 'ค้นหาประเทศ',
    countryEmpty: 'ไม่พบผลลัพธ์',
    growthRef: 'ประเทศอ้างอิงการเจริญเติบโต',
    growthRefHint: 'จะเปรียบเทียบกับเด็กประเทศไหน? ปกติเป็นประเทศเดียวกับที่อาศัยอยู่ครับ',
    fatherH: 'ส่วนสูงของพ่อ (ซม.)',
    motherH: 'ส่วนสูงของแม่ (ซม.)',
    desiredH: 'ส่วนสูงที่ต้องการ (ซม.)',
    currentH: 'ส่วนสูงปัจจุบัน (ซม.)',
    currentW: 'น้ำหนักปัจจุบัน (กก.)',
    grade: 'ระดับชั้น',
    classRank: 'ลำดับส่วนสูงในชั้น',
    phone: 'เบอร์โทรศัพท์',
    email: 'อีเมล',
    address: 'ที่อยู่',
    gestWeeks: 'อายุครรภ์ตอนคลอด (สัปดาห์)',
    birthWeight: 'น้ำหนักแรกเกิด (กก.)',
    birthNote: 'ภาวะพิเศษตอนแรกเกิด (ถ้ามี)',
    growthHint: 'กรุณากรอกข้อมูลจากสมุดพัฒนาการหรือเวชระเบียนกุมารแพทย์',
    ageCol: 'อายุ (ชั้นเรียน)',
    heightCol: 'ส่วนสูง (ซม.)',
    yearlyGrowth: 'ส่วนสูงที่เพิ่มขึ้นใน 1 ปีที่ผ่านมา (ซม.)',
    flagRapid: 'ช่วงนี้สูงขึ้นเร็วผิดปกติ',
    flagSlowed: 'การเจริญเติบโตชะลอลงอย่างเห็นได้ชัด',
    flagPuberty: 'กังวลเรื่องวัยรุ่นก่อนกำหนด',
    yes: 'ใช่',
    no: 'ไม่ใช่',
    pastConsult: 'เคยปรึกษาคลินิกด้านการเจริญเติบโตมาก่อนหรือไม่?',
    parentsInterested: 'ผู้ปกครองทั้งสองฝ่ายสนใจเรื่องการดูแลการเจริญเติบโตหรือไม่?',
    sportsAthlete: 'เด็กเป็นนักกีฬาหรือสมาชิกทีมกีฬาหรือไม่?',
    sportsEvent: 'ชนิดกีฬา',
    childInterested: 'เด็กสนใจที่จะสูงขึ้นด้วยตนเองหรือไม่?',
    acquisitionChannel: 'คุณรู้จักเราได้อย่างไร?',
    acquisitionChannelOpts: [
      { value: 'google', label: 'ค้นหา Google' },
      { value: 'instagram', label: 'Instagram' },
      { value: 'facebook', label: 'Facebook' },
      { value: 'youtube', label: 'YouTube' },
      { value: 'referral', label: 'แนะนำจากคนรู้จัก' },
      { value: 'ai', label: 'AI (เช่น ChatGPT)' },
      { value: 'other', label: 'อื่นๆ' },
    ],
    sLifeTitle: 'พฤติกรรมการใช้ชีวิต',
    sleepTime: 'เวลาเข้านอน',
    wakeTime: 'เวลาตื่นนอน',
    exerciseFreq: 'ความถี่ในการออกกำลังกาย',
    exerciseOpts: [
      { value: 'none', label: 'แทบไม่ออกกำลังกาย' },
      { value: 'week1_2', label: '1–2 ครั้ง/สัปดาห์' },
      { value: 'week3_4', label: '3–4 ครั้ง/สัปดาห์' },
      { value: 'daily', label: 'ทุกวัน' },
    ],
    milkDaily: 'การดื่มนม / ผลิตภัณฑ์จากนม',
    milkOpts: [
      { value: 'none', label: 'แทบไม่ดื่ม' },
      { value: 'sometimes', label: 'บางครั้ง (2–3 ครั้ง/สัปดาห์)' },
      { value: 'daily1', label: 'วันละ 1 แก้ว' },
      { value: 'daily2plus', label: 'วันละ 2 แก้วขึ้นไป' },
    ],
    mealReg: 'ความสม่ำเสมอของมื้ออาหาร',
    mealOpts: [
      { value: 'irregular', label: 'ไม่สม่ำเสมอ' },
      { value: 'mostly_regular', label: 'ค่อนข้างสม่ำเสมอ' },
      { value: 'very_regular', label: 'สม่ำเสมอมาก' },
    ],
    chronic: 'กรุณาระบุโรคประจำตัวหรือโรคที่กำลังรักษาอยู่ (ถ้ามี)',
    tanner: 'ระยะวัยรุ่น (Tanner Stage)',
    tannerOpts: [
      'ระยะที่ 1 — ยังไม่มีสัญญาณวัยรุ่น',
      'ระยะที่ 2 — เริ่มมีการเปลี่ยนแปลงในช่วงวัยรุ่น',
      'ระยะที่ 3 — มีการเปลี่ยนแปลงอย่างชัดเจน',
      'ระยะที่ 4 — ใกล้เสร็จสิ้นวัยรุ่นแล้ว',
      'ระยะที่ 5 — วัยรุ่นสมบูรณ์, ร่างกายผู้ใหญ่',
    ],
    currentMeds: 'ยาหรืออาหารเสริมที่รับประทานอยู่',
    voiceChange: 'เสียงแตกหนุ่ม (เสียงเปลี่ยน)',
    voiceOpts: [
      { value: 'none', label: 'ยังไม่มี' },
      { value: 'started', label: 'เริ่มแล้ว' },
      { value: 'done', label: 'เสียงเปลี่ยนสมบูรณ์แล้ว' },
    ],
    facialHair: 'หนวด / ขนตามร่างกาย',
    facialOpts: [
      { value: 'none', label: 'ไม่มี' },
      { value: 'fuzz', label: 'มีขนอ่อนเล็กน้อย' },
      { value: 'clear', label: 'เห็นได้ชัดเจน' },
    ],
    menarche: 'ประจำเดือนครั้งแรก',
    menarcheOpts: [
      { value: 'none', label: 'ยังไม่มี' },
      { value: 'recent6m', label: 'เริ่มแล้ว (ภายใน 6 เดือนที่ผ่านมา)' },
      { value: 'over1y', label: 'มามากกว่า 1 ปีแล้ว' },
    ],
    breastDev: 'พัฒนาการของเต้านม',
    breastOpts: [
      { value: 'none', label: 'ยังไม่เริ่ม' },
      { value: 'budding', label: 'เริ่มเป็นตุ่มเล็ก' },
      { value: 'clear', label: 'พัฒนาชัดเจน' },
    ],
    causes: 'สาเหตุที่ทำให้ส่วนสูงน้อย (เลือกได้หลายข้อ)',
    causeOpts: [
      { value: 'parents_short', label: 'พ่อแม่ตัวเตี้ย' },
      { value: 'parents_height_gap', label: 'ส่วนสูงน้อยกว่าที่คาดจากพ่อแม่' },
      { value: 'picky_eating', label: 'กินอาหารเลือก / ทานน้อย' },
      { value: 'parents_early_stop', label: 'พ่อหรือแม่หยุดสูงเร็วผิดปกติ' },
      { value: 'insufficient_sleep', label: 'นอนหลับไม่เพียงพอ' },
      { value: 'chronic_illness', label: 'มีโรคประจำตัว' },
    ],
    causesOther: 'สาเหตุอื่น ๆ',
    additionalNotes: 'หมายเหตุเพิ่มเติม (ข้อสงสัยหรือข้อมูลอ้างอิง)',
    xrayUpload: 'แนบไฟล์ X-ray',
    labUpload: 'แนบผลตรวจเลือดหรือผลแล็บ',
    uploadHint: 'แนบรูปภาพหรือไฟล์ PDF (ไม่บังคับ)',
  },

  vi: {
    pageTitle: 'Phiếu khảo sát trước khám — 187 Growth Clinic',
    stepOf: (n, t) => `Bước ${n} / ${t}`,
    next: 'Tiếp theo',
    prev: 'Quay lại',
    submit: 'Gửi phiếu',
    submitting: 'Đang gửi...',
    doneTitle: 'Cảm ơn bạn',
    doneBody: 'Phiếu khảo sát đã được tiếp nhận. Chúng tôi sẽ liên hệ sớm.',
    retry: 'Thử lại',
    required: 'Vui lòng điền thông tin này',
    invalidBirth: 'Ngày sinh không hợp lệ. Vui lòng kiểm tra lại.',
    submitError: 'Đã xảy ra lỗi khi gửi. Vui lòng kiểm tra thông tin và thử lại.',
    s1Title: 'Thông tin cơ bản',
    s2Title: 'Lịch sử tăng trưởng',
    s3Title: 'Gia đình · Mức độ quan tâm',
    s4Title: 'Sức khỏe · Phát triển',
    s5Title: 'Nguyên nhân thấp còi',
    s6Title: 'Đính kèm file kết quả',
    name: 'Họ và tên',
    nameEn: 'Tên tiếng Anh',
    gender: 'Giới tính',
    male: 'Bé trai',
    female: 'Bé gái',
    birth: 'Ngày sinh',
    year: 'Năm',
    month: 'Tháng',
    day: 'Ngày',
    country: 'Quốc gia cư trú',
    countrySearch: 'Tìm quốc gia',
    countryEmpty: 'Không có kết quả',
    growthRef: 'Quốc gia tham chiếu tăng trưởng',
    growthRefHint: 'So sánh với trẻ em nước nào? Thường trùng với nơi bạn sống.',
    fatherH: 'Chiều cao của bố (cm)',
    motherH: 'Chiều cao của mẹ (cm)',
    desiredH: 'Chiều cao mong muốn (cm)',
    currentH: 'Chiều cao hiện tại (cm)',
    currentW: 'Cân nặng hiện tại (kg)',
    grade: 'Lớp học',
    classRank: 'Thứ hạng chiều cao trong lớp',
    phone: 'Số điện thoại',
    email: 'Email',
    address: 'Địa chỉ',
    gestWeeks: 'Tuần thai khi sinh (tuần)',
    birthWeight: 'Cân nặng khi sinh (kg)',
    birthNote: 'Điểm đặc biệt khi sinh (nếu có)',
    growthHint: 'Vui lòng điền dựa trên học bạ hoặc hồ sơ y tế nhi khoa.',
    ageCol: 'Tuổi (lớp)',
    heightCol: 'Chiều cao (cm)',
    yearlyGrowth: 'Chiều cao tăng trong 1 năm qua (cm)',
    flagRapid: 'Gần đây tăng chiều cao rất nhanh',
    flagSlowed: 'Tốc độ tăng trưởng giảm rõ rệt gần đây',
    flagPuberty: 'Lo lắng về dậy thì sớm',
    yes: 'Có',
    no: 'Không',
    pastConsult: 'Trước đây có từng tư vấn tại phòng khám tăng trưởng chưa?',
    parentsInterested: 'Cả hai phụ huynh có quan tâm đến việc theo dõi tăng trưởng không?',
    sportsAthlete: 'Trẻ có tham gia đội thể thao hoặc là vận động viên không?',
    sportsEvent: 'Môn thể thao',
    childInterested: 'Bản thân trẻ có muốn cao hơn không?',
    acquisitionChannel: 'Bạn biết đến chúng tôi qua đâu?',
    acquisitionChannelOpts: [
      { value: 'google', label: 'Tìm kiếm Google' },
      { value: 'instagram', label: 'Instagram' },
      { value: 'facebook', label: 'Facebook' },
      { value: 'youtube', label: 'YouTube' },
      { value: 'referral', label: 'Người quen giới thiệu' },
      { value: 'ai', label: 'AI (ChatGPT, v.v.)' },
      { value: 'other', label: 'Khác' },
    ],
    sLifeTitle: 'Thói quen sinh hoạt',
    sleepTime: 'Giờ đi ngủ',
    wakeTime: 'Giờ thức dậy',
    exerciseFreq: 'Tần suất vận động',
    exerciseOpts: [
      { value: 'none', label: 'Hầu như không' },
      { value: 'week1_2', label: '1–2 lần/tuần' },
      { value: 'week3_4', label: '3–4 lần/tuần' },
      { value: 'daily', label: 'Hằng ngày' },
    ],
    milkDaily: 'Uống sữa / chế phẩm từ sữa',
    milkOpts: [
      { value: 'none', label: 'Hầu như không' },
      { value: 'sometimes', label: 'Thỉnh thoảng (2–3 lần/tuần)' },
      { value: 'daily1', label: 'Mỗi ngày 1 ly' },
      { value: 'daily2plus', label: 'Mỗi ngày từ 2 ly trở lên' },
    ],
    mealReg: 'Mức độ đều đặn của bữa ăn',
    mealOpts: [
      { value: 'irregular', label: 'Không đều đặn' },
      { value: 'mostly_regular', label: 'Khá đều đặn' },
      { value: 'very_regular', label: 'Rất đều đặn' },
    ],
    chronic: 'Vui lòng ghi lại bệnh lý đang điều trị hoặc bệnh mãn tính (nếu có).',
    tanner: 'Giai đoạn dậy thì (Tanner Stage)',
    tannerOpts: [
      'Giai đoạn 1 — Chưa có dấu hiệu dậy thì',
      'Giai đoạn 2 — Bắt đầu có thay đổi dậy thì',
      'Giai đoạn 3 — Thay đổi rõ ràng đang diễn ra',
      'Giai đoạn 4 — Gần hoàn tất dậy thì',
      'Giai đoạn 5 — Dậy thì hoàn toàn, cơ thể người lớn',
    ],
    currentMeds: 'Thuốc / thực phẩm chức năng đang dùng',
    voiceChange: 'Vỡ giọng (thay đổi giọng nói)',
    voiceOpts: [
      { value: 'none', label: 'Chưa có' },
      { value: 'started', label: 'Đã bắt đầu' },
      { value: 'done', label: 'Đã hoàn tất' },
    ],
    facialHair: 'Râu / lông trên cơ thể',
    facialOpts: [
      { value: 'none', label: 'Không có' },
      { value: 'fuzz', label: 'Lông tơ nhẹ' },
      { value: 'clear', label: 'Rõ rệt' },
    ],
    menarche: 'Kinh nguyệt lần đầu',
    menarcheOpts: [
      { value: 'none', label: 'Chưa có' },
      { value: 'recent6m', label: 'Đã bắt đầu (trong 6 tháng gần đây)' },
      { value: 'over1y', label: 'Đã hơn 1 năm' },
    ],
    breastDev: 'Phát triển ngực',
    breastOpts: [
      { value: 'none', label: 'Chưa phát triển' },
      { value: 'budding', label: 'Bắt đầu nhú' },
      { value: 'clear', label: 'Phát triển rõ' },
    ],
    causes: 'Nguyên nhân thấp còi (có thể chọn nhiều)',
    causeOpts: [
      { value: 'parents_short', label: 'Bố mẹ thấp' },
      { value: 'parents_height_gap', label: 'Thấp hơn kỳ vọng so với chiều cao bố mẹ' },
      { value: 'picky_eating', label: 'Ăn kén / ăn ít' },
      { value: 'parents_early_stop', label: 'Bố hoặc mẹ ngừng phát triển chiều cao sớm' },
      { value: 'insufficient_sleep', label: 'Ngủ không đủ giấc' },
      { value: 'chronic_illness', label: 'Có bệnh mãn tính' },
    ],
    causesOther: 'Nguyên nhân khác',
    additionalNotes: 'Ghi chú thêm (thắc mắc hoặc thông tin tham khảo)',
    xrayUpload: 'Đính kèm file X-quang',
    labUpload: 'Đính kèm kết quả xét nghiệm',
    uploadHint: 'Vui lòng đính kèm ảnh hoặc file PDF (không bắt buộc).',
  },

  en: {
    pageTitle: '187 Growth Clinic — Pre-visit Survey',
    stepOf: (n, t) => `Step ${n} of ${t}`,
    next: 'Next',
    prev: 'Back',
    submit: 'Submit',
    submitting: 'Submitting...',
    doneTitle: 'Thank you',
    doneBody: 'Your survey has been received. We will be in touch shortly.',
    retry: 'Try again',
    required: 'This field is required',
    invalidBirth: 'Please enter a valid date of birth.',
    submitError: 'Something went wrong while submitting. Please check your entries and try again.',
    s1Title: 'Basic Information',
    s2Title: 'Growth History',
    s3Title: 'Family & Interest',
    s4Title: 'Medical & Development',
    s5Title: 'Causes of Short Stature',
    s6Title: 'Attach Test Files',
    name: 'Full name',
    nameEn: 'Name (English)',
    gender: 'Gender',
    male: 'Boy',
    female: 'Girl',
    birth: 'Date of birth',
    year: 'Year',
    month: 'Month',
    day: 'Day',
    country: 'Country of residence',
    countrySearch: 'Search country',
    countryEmpty: 'No results',
    growthRef: 'Growth reference country',
    growthRefHint: 'Which country’s children should we compare with? Usually the same as where you live.',
    fatherH: "Father's height (cm)",
    motherH: "Mother's height (cm)",
    desiredH: 'Desired height (cm)',
    currentH: 'Current height (cm)',
    currentW: 'Current weight (kg)',
    grade: 'School grade',
    classRank: 'Height rank in class',
    phone: 'Phone number',
    email: 'Email',
    address: 'Address',
    gestWeeks: 'Gestational age at birth (weeks)',
    birthWeight: 'Birth weight (kg)',
    birthNote: 'Anything notable at birth',
    growthHint: 'Please fill in from school health records or pediatric medical records.',
    ageCol: 'Age (grade)',
    heightCol: 'Height (cm)',
    yearlyGrowth: 'Height gained in the past year (cm)',
    flagRapid: 'Has grown unusually fast recently',
    flagSlowed: 'Growth rate has slowed significantly recently',
    flagPuberty: 'Concerned about early puberty',
    yes: 'Yes',
    no: 'No',
    pastConsult: 'Has the child previously consulted a growth clinic?',
    parentsInterested: 'Are both parents interested in growth management?',
    sportsAthlete: 'Is the child a member of a sports team or competitive athlete?',
    sportsEvent: 'Sport',
    childInterested: 'Is the child personally motivated to grow taller?',
    acquisitionChannel: 'How did you hear about us?',
    acquisitionChannelOpts: [
      { value: 'google', label: 'Google search' },
      { value: 'instagram', label: 'Instagram' },
      { value: 'facebook', label: 'Facebook' },
      { value: 'youtube', label: 'YouTube' },
      { value: 'referral', label: 'Friend/family referral' },
      { value: 'ai', label: 'AI (ChatGPT, etc.)' },
      { value: 'other', label: 'Other' },
    ],
    sLifeTitle: 'Lifestyle',
    sleepTime: 'Bedtime',
    wakeTime: 'Wake-up time',
    exerciseFreq: 'Exercise frequency',
    exerciseOpts: [
      { value: 'none', label: 'Rarely' },
      { value: 'week1_2', label: '1–2 times a week' },
      { value: 'week3_4', label: '3–4 times a week' },
      { value: 'daily', label: 'Every day' },
    ],
    milkDaily: 'Milk / dairy intake',
    milkOpts: [
      { value: 'none', label: 'Rarely' },
      { value: 'sometimes', label: 'Sometimes (2–3 times a week)' },
      { value: 'daily1', label: '1 glass daily' },
      { value: 'daily2plus', label: '2+ glasses daily' },
    ],
    mealReg: 'Meal regularity',
    mealOpts: [
      { value: 'irregular', label: 'Irregular' },
      { value: 'mostly_regular', label: 'Mostly regular' },
      { value: 'very_regular', label: 'Very regular' },
    ],
    chronic: 'Please list any ongoing or past medical conditions being treated.',
    tanner: 'Puberty stage (Tanner Stage)',
    tannerOpts: [
      'Stage 1 — No signs of puberty yet',
      'Stage 2 — Puberty just beginning',
      'Stage 3 — Noticeable changes underway',
      'Stage 4 — Puberty nearly complete',
      'Stage 5 — Puberty complete, adult body',
    ],
    currentMeds: 'Current medications / supplements',
    voiceChange: 'Voice change (voice breaking)',
    voiceOpts: [
      { value: 'none', label: 'Not yet' },
      { value: 'started', label: 'Started' },
      { value: 'done', label: 'Complete' },
    ],
    facialHair: 'Facial / body hair',
    facialOpts: [
      { value: 'none', label: 'None' },
      { value: 'fuzz', label: 'Light fuzz' },
      { value: 'clear', label: 'Clearly visible' },
    ],
    menarche: 'First menstruation',
    menarcheOpts: [
      { value: 'none', label: 'Not yet' },
      { value: 'recent6m', label: 'Started (within the last 6 months)' },
      { value: 'over1y', label: 'More than 1 year ago' },
    ],
    breastDev: 'Breast development',
    breastOpts: [
      { value: 'none', label: 'Not started' },
      { value: 'budding', label: 'Budding' },
      { value: 'clear', label: 'Clearly developed' },
    ],
    causes: 'Possible causes of short stature (select all that apply)',
    causeOpts: [
      { value: 'parents_short', label: 'Parents are short' },
      { value: 'parents_height_gap', label: 'Shorter than expected from parents\' height' },
      { value: 'picky_eating', label: 'Picky eating / insufficient food intake' },
      { value: 'parents_early_stop', label: 'A parent stopped growing early' },
      { value: 'insufficient_sleep', label: 'Insufficient sleep' },
      { value: 'chronic_illness', label: 'Chronic illness' },
    ],
    causesOther: 'Other causes',
    additionalNotes: 'Additional notes (questions or anything else)',
    xrayUpload: 'Attach X-ray file',
    labUpload: 'Attach lab results',
    uploadHint: 'Please attach an image or PDF file (optional).',
  },

  'zh-hans': {
    pageTitle: '187 成长诊所 — 就诊前问卷',
    stepOf: (n, t) => `第 ${n} / ${t} 步`,
    next: '下一步',
    prev: '上一步',
    submit: '提交',
    submitting: '提交中...',
    doneTitle: '感谢您',
    doneBody: '问卷已收到，我们会尽快与您联系。',
    retry: '重试',
    required: '此项为必填',
    invalidBirth: '出生日期无效，请重新确认。',
    submitError: '提交时出现问题，请检查填写内容后重试。',
    s1Title: '基本信息',
    s2Title: '成长记录',
    s3Title: '家庭 · 关注度',
    s4Title: '病史 · 发育',
    s5Title: '身高偏矮的原因',
    s6Title: '上传检查文件',
    name: '姓名',
    nameEn: '英文姓名',
    gender: '性别',
    male: '男孩',
    female: '女孩',
    birth: '出生日期',
    year: '年',
    month: '月',
    day: '日',
    country: '居住国',
    countrySearch: '国を検索',
    countryEmpty: '該当なし',
    growthRef: '成長基準の国',
    growthRefHint: 'どの国の子どもと比べて予測しますか？通常はお住まいの国と同じです。',
    fatherH: '父亲身高 (cm)',
    motherH: '母亲身高 (cm)',
    desiredH: '期望身高 (cm)',
    currentH: '当前身高 (cm)',
    currentW: '当前体重 (kg)',
    grade: '年级',
    classRank: '班级身高排名',
    phone: '联系电话',
    email: '电子邮箱',
    address: '居住地',
    gestWeeks: '出生时孕周 (周)',
    birthWeight: '出生体重 (kg)',
    birthNote: '出生时特殊情况（如有）',
    growthHint: '请参考学生健康记录或儿科病历填写。',
    ageCol: '年龄（年级）',
    heightCol: '身高 (cm)',
    yearlyGrowth: '过去一年长高的身高 (cm)',
    flagRapid: '最近身高长得特别快',
    flagSlowed: '最近生长速度明显放缓',
    flagPuberty: '担心性早熟',
    yes: '是',
    no: '否',
    pastConsult: '孩子以前是否在成长诊所咨询过？',
    parentsInterested: '父母双方是否都关注孩子的成长管理？',
    sportsAthlete: '孩子是否为体育特长生或运动队成员？',
    sportsEvent: '项目',
    childInterested: '孩子本人是否也希望长高？',
    acquisitionChannel: '您是如何了解到我们的？',
    acquisitionChannelOpts: [
      { value: 'google', label: 'Google 搜索' },
      { value: 'instagram', label: 'Instagram' },
      { value: 'facebook', label: 'Facebook' },
      { value: 'youtube', label: 'YouTube' },
      { value: 'referral', label: '熟人介绍' },
      { value: 'ai', label: 'AI（如 ChatGPT）' },
      { value: 'other', label: '其他' },
    ],
    sLifeTitle: '生活习惯',
    sleepTime: '就寝时间',
    wakeTime: '起床时间',
    exerciseFreq: '运动频率',
    exerciseOpts: [
      { value: 'none', label: '几乎不运动' },
      { value: 'week1_2', label: '每周 1~2 次' },
      { value: 'week3_4', label: '每周 3~4 次' },
      { value: 'daily', label: '每天' },
    ],
    milkDaily: '牛奶 / 乳制品摄入',
    milkOpts: [
      { value: 'none', label: '几乎不喝' },
      { value: 'sometimes', label: '偶尔（每周 2~3 次）' },
      { value: 'daily1', label: '每天 1 杯' },
      { value: 'daily2plus', label: '每天 2 杯以上' },
    ],
    mealReg: '饮食规律性',
    mealOpts: [
      { value: 'irregular', label: '不规律' },
      { value: 'mostly_regular', label: '基本规律' },
      { value: 'very_regular', label: '非常规律' },
    ],
    chronic: '如有正在治疗或过去治疗过的疾病，请填写。',
    tanner: '青春期阶段 (Tanner 分期)',
    tannerOpts: [
      '第 1 期 — 尚无青春期变化',
      '第 2 期 — 青春期变化刚开始',
      '第 3 期 — 变化明显进行中',
      '第 4 期 — 青春期接近完成',
      '第 5 期 — 青春期完成，成人体型',
    ],
    currentMeds: '目前服用的药物 / 保健品',
    voiceChange: '变声（嗓音变化）',
    voiceOpts: [
      { value: 'none', label: '尚未开始' },
      { value: 'started', label: '已开始' },
      { value: 'done', label: '已完成' },
    ],
    facialHair: '胡须 / 体毛',
    facialOpts: [
      { value: 'none', label: '没有' },
      { value: 'fuzz', label: '有一点绒毛' },
      { value: 'clear', label: '明显可见' },
    ],
    menarche: '初潮情况',
    menarcheOpts: [
      { value: 'none', label: '尚未来潮' },
      { value: 'recent6m', label: '已开始（最近 6 个月内）' },
      { value: 'over1y', label: '已超过 1 年' },
    ],
    breastDev: '乳房发育',
    breastOpts: [
      { value: 'none', label: '尚未发育' },
      { value: 'budding', label: '开始隆起' },
      { value: 'clear', label: '发育明显' },
    ],
    causes: '身高偏矮的原因（可多选）',
    causeOpts: [
      { value: 'parents_short', label: '父母身高偏矮' },
      { value: 'parents_height_gap', label: '比按父母身高预期的更矮' },
      { value: 'picky_eating', label: '挑食 / 进食不足' },
      { value: 'parents_early_stop', label: '父母小时候过早停止长高' },
      { value: 'insufficient_sleep', label: '睡眠不足' },
      { value: 'chronic_illness', label: '有慢性疾病' },
    ],
    causesOther: '其他原因',
    additionalNotes: '补充说明（疑问或参考事项）',
    xrayUpload: '上传 X 光文件',
    labUpload: '上传检查结果',
    uploadHint: '请上传图片或 PDF 文件（选填）。',
  },

  'zh-hant': {
    pageTitle: '187 成長診所 — 就診前問卷',
    stepOf: (n, t) => `第 ${n} / ${t} 步`,
    next: '下一步',
    prev: '上一步',
    submit: '送出',
    submitting: '送出中...',
    doneTitle: '感謝您',
    doneBody: '問卷已收到，我們會盡快與您聯繫。',
    retry: '重試',
    required: '此項為必填',
    invalidBirth: '出生日期無效，請重新確認。',
    submitError: '提交時發生問題，請檢查填寫內容後重試。',
    s1Title: '基本資料',
    s2Title: '成長紀錄',
    s3Title: '家庭 · 關注度',
    s4Title: '病史 · 發育',
    s5Title: '身高偏矮的原因',
    s6Title: '上傳檢查檔案',
    name: '姓名',
    nameEn: '英文姓名',
    gender: '性別',
    male: '男孩',
    female: '女孩',
    birth: '出生日期',
    year: '年',
    month: '月',
    day: '日',
    country: '居住國家',
    countrySearch: '搜尋國家',
    countryEmpty: '沒有結果',
    growthRef: '生長基準國家',
    growthRefHint: '要與哪個國家的孩子比較？通常與您居住的國家相同。',
    fatherH: '父親身高 (cm)',
    motherH: '母親身高 (cm)',
    desiredH: '期望身高 (cm)',
    currentH: '目前身高 (cm)',
    currentW: '目前體重 (kg)',
    grade: '年級',
    classRank: '班級身高排名',
    phone: '聯絡電話',
    email: '電子郵件',
    address: '居住地',
    gestWeeks: '出生時孕週 (週)',
    birthWeight: '出生體重 (kg)',
    birthNote: '出生時特殊情況（如有）',
    growthHint: '請參考學生健康紀錄或兒科病歷填寫。',
    ageCol: '年齡（年級）',
    heightCol: '身高 (cm)',
    yearlyGrowth: '過去一年長高的身高 (cm)',
    flagRapid: '最近身高長得特別快',
    flagSlowed: '最近生長速度明顯趨緩',
    flagPuberty: '擔心性早熟',
    yes: '是',
    no: '否',
    pastConsult: '孩子以前是否曾在成長診所諮詢過？',
    parentsInterested: '父母雙方是否都關注孩子的成長管理？',
    sportsAthlete: '孩子是否為體育專長生或運動隊成員？',
    sportsEvent: '項目',
    childInterested: '孩子本人是否也希望長高？',
    acquisitionChannel: '您是如何得知我們的？',
    acquisitionChannelOpts: [
      { value: 'google', label: 'Google 搜尋' },
      { value: 'instagram', label: 'Instagram' },
      { value: 'facebook', label: 'Facebook' },
      { value: 'youtube', label: 'YouTube' },
      { value: 'referral', label: '熟人介紹' },
      { value: 'ai', label: 'AI（如 ChatGPT）' },
      { value: 'other', label: '其他' },
    ],
    sLifeTitle: '生活習慣',
    sleepTime: '就寢時間',
    wakeTime: '起床時間',
    exerciseFreq: '運動頻率',
    exerciseOpts: [
      { value: 'none', label: '幾乎不運動' },
      { value: 'week1_2', label: '每週 1~2 次' },
      { value: 'week3_4', label: '每週 3~4 次' },
      { value: 'daily', label: '每天' },
    ],
    milkDaily: '牛奶 / 乳製品攝取',
    milkOpts: [
      { value: 'none', label: '幾乎不喝' },
      { value: 'sometimes', label: '偶爾（每週 2~3 次）' },
      { value: 'daily1', label: '每天 1 杯' },
      { value: 'daily2plus', label: '每天 2 杯以上' },
    ],
    mealReg: '飲食規律性',
    mealOpts: [
      { value: 'irregular', label: '不規律' },
      { value: 'mostly_regular', label: '大致規律' },
      { value: 'very_regular', label: '非常規律' },
    ],
    chronic: '如有正在治療或過去治療過的疾病，請填寫。',
    tanner: '青春期階段 (Tanner 分期)',
    tannerOpts: [
      '第 1 期 — 尚無青春期變化',
      '第 2 期 — 青春期變化剛開始',
      '第 3 期 — 變化明顯進行中',
      '第 4 期 — 青春期接近完成',
      '第 5 期 — 青春期完成，成人體型',
    ],
    currentMeds: '目前服用的藥物 / 保健品',
    voiceChange: '變聲（嗓音變化）',
    voiceOpts: [
      { value: 'none', label: '尚未開始' },
      { value: 'started', label: '已開始' },
      { value: 'done', label: '已完成' },
    ],
    facialHair: '鬍鬚 / 體毛',
    facialOpts: [
      { value: 'none', label: '沒有' },
      { value: 'fuzz', label: '有一點絨毛' },
      { value: 'clear', label: '明顯可見' },
    ],
    menarche: '初經情況',
    menarcheOpts: [
      { value: 'none', label: '尚未來經' },
      { value: 'recent6m', label: '已開始（最近 6 個月內）' },
      { value: 'over1y', label: '已超過 1 年' },
    ],
    breastDev: '乳房發育',
    breastOpts: [
      { value: 'none', label: '尚未發育' },
      { value: 'budding', label: '開始隆起' },
      { value: 'clear', label: '發育明顯' },
    ],
    causes: '身高偏矮的原因（可複選）',
    causeOpts: [
      { value: 'parents_short', label: '父母身高偏矮' },
      { value: 'parents_height_gap', label: '比依父母身高預期的更矮' },
      { value: 'picky_eating', label: '挑食 / 進食不足' },
      { value: 'parents_early_stop', label: '父母小時候過早停止長高' },
      { value: 'insufficient_sleep', label: '睡眠不足' },
      { value: 'chronic_illness', label: '有慢性疾病' },
    ],
    causesOther: '其他原因',
    additionalNotes: '補充說明（疑問或參考事項）',
    xrayUpload: '上傳 X 光檔案',
    labUpload: '上傳檢查結果',
    uploadHint: '請上傳圖片或 PDF 檔案（選填）。',
  },

  ja: {
    pageTitle: '187 成長クリニック — 受診前問診',
    stepOf: (n, t) => `${n} / ${t} ステップ`,
    next: '次へ',
    prev: '戻る',
    submit: '送信する',
    submitting: '送信中...',
    doneTitle: 'ありがとうございます',
    doneBody: '問診票を受け付けました。追ってご連絡いたします。',
    retry: '再試行',
    required: '必須項目です',
    invalidBirth: '生年月日が正しくありません。ご確認ください。',
    submitError: '送信中に問題が発生しました。入力内容をご確認のうえ再度お試しください。',
    s1Title: '基本情報',
    s2Title: '成長の記録',
    s3Title: '家族 · 関心度',
    s4Title: '既往歴 · 発育',
    s5Title: '低身長の原因',
    s6Title: '検査ファイルの添付',
    name: '氏名',
    nameEn: '氏名（英語）',
    gender: '性別',
    male: '男の子',
    female: '女の子',
    birth: '生年月日',
    year: '年',
    month: '月',
    day: '日',
    country: '居住国家',
    countrySearch: '搜索国家',
    countryEmpty: '没有结果',
    growthRef: '生长基准国家',
    growthRefHint: '要与哪个国家的孩子比较？通常与您居住的国家相同。',
    fatherH: '父親の身長 (cm)',
    motherH: '母親の身長 (cm)',
    desiredH: '希望身長 (cm)',
    currentH: '現在の身長 (cm)',
    currentW: '現在の体重 (kg)',
    grade: '学年',
    classRank: 'クラス内の身長順',
    phone: '電話番号',
    email: 'メールアドレス',
    address: 'お住まい',
    gestWeeks: '出生時の在胎週数（週）',
    birthWeight: '出生時の体重 (kg)',
    birthNote: '出生時の特記事項（あれば）',
    growthHint: '学校の健康記録や小児科の記録を参考にご記入ください。',
    ageCol: '年齢（学年）',
    heightCol: '身長 (cm)',
    yearlyGrowth: '直近1年で伸びた身長 (cm)',
    flagRapid: '最近、身長が急に伸びている',
    flagSlowed: '最近、成長のペースが明らかに落ちた',
    flagPuberty: '思春期早発症が心配',
    yes: 'はい',
    no: 'いいえ',
    pastConsult: 'これまでに成長クリニックで相談したことはありますか？',
    parentsInterested: 'ご両親とも成長管理に関心がありますか？',
    sportsAthlete: 'お子さまはスポーツの選手・チーム所属ですか？',
    sportsEvent: '競技種目',
    childInterested: 'お子さま自身も背を伸ばしたいと思っていますか？',
    acquisitionChannel: '当院をどこで知りましたか？',
    acquisitionChannelOpts: [
      { value: 'google', label: 'Google 検索' },
      { value: 'instagram', label: 'Instagram' },
      { value: 'facebook', label: 'Facebook' },
      { value: 'youtube', label: 'YouTube' },
      { value: 'referral', label: '知人の紹介' },
      { value: 'ai', label: 'AI（ChatGPT など）' },
      { value: 'other', label: 'その他' },
    ],
    sLifeTitle: '生活習慣',
    sleepTime: '就寝時刻',
    wakeTime: '起床時刻',
    exerciseFreq: '運動の頻度',
    exerciseOpts: [
      { value: 'none', label: 'ほとんどしない' },
      { value: 'week1_2', label: '週に1〜2回' },
      { value: 'week3_4', label: '週に3〜4回' },
      { value: 'daily', label: '毎日' },
    ],
    milkDaily: '牛乳・乳製品の摂取',
    milkOpts: [
      { value: 'none', label: 'ほとんど飲まない' },
      { value: 'sometimes', label: 'ときどき（週2〜3回）' },
      { value: 'daily1', label: '毎日1杯' },
      { value: 'daily2plus', label: '毎日2杯以上' },
    ],
    mealReg: '食事の規則性',
    mealOpts: [
      { value: 'irregular', label: '不規則' },
      { value: 'mostly_regular', label: 'おおむね規則的' },
      { value: 'very_regular', label: 'とても規則的' },
    ],
    chronic: '現在または過去に治療中の疾患があればご記入ください。',
    tanner: '思春期の段階 (Tanner 段階)',
    tannerOpts: [
      '第1段階 — まだ思春期の変化なし',
      '第2段階 — 思春期の変化が始まったばかり',
      '第3段階 — 変化が目立って進行中',
      '第4段階 — 思春期がほぼ完成',
      '第5段階 — 思春期が完了、成人の体型',
    ],
    currentMeds: '現在服用中の薬・サプリメント',
    voiceChange: '声変わり（声の変化）',
    voiceOpts: [
      { value: 'none', label: 'まだない' },
      { value: 'started', label: '始まった' },
      { value: 'done', label: '完了した' },
    ],
    facialHair: 'ひげ・体毛',
    facialOpts: [
      { value: 'none', label: 'なし' },
      { value: 'fuzz', label: 'うぶ毛程度' },
      { value: 'clear', label: 'はっきりある' },
    ],
    menarche: '初経の有無',
    menarcheOpts: [
      { value: 'none', label: 'まだない' },
      { value: 'recent6m', label: '始まった（直近6か月以内）' },
      { value: 'over1y', label: '1年以上経過' },
    ],
    breastDev: '乳房の発達',
    breastOpts: [
      { value: 'none', label: '発達前' },
      { value: 'budding', label: 'ふくらみ始め' },
      { value: 'clear', label: 'はっきり発達' },
    ],
    causes: '低身長の原因（該当するものすべて選択）',
    causeOpts: [
      { value: 'parents_short', label: '両親の身長が低い' },
      { value: 'parents_height_gap', label: '両親の身長からの予想より低い' },
      { value: 'picky_eating', label: '偏食・食事量が不足' },
      { value: 'parents_early_stop', label: '親が子どもの頃に早く成長が止まった' },
      { value: 'insufficient_sleep', label: '睡眠時間が不足' },
      { value: 'chronic_illness', label: '慢性疾患がある' },
    ],
    causesOther: 'その他の原因',
    additionalNotes: '追加メモ（ご質問・参考事項）',
    xrayUpload: 'X線ファイルの添付',
    labUpload: '検査結果の添付',
    uploadHint: '画像または PDF ファイルを添付してください（任意）。',
  },

  es: {
    pageTitle: '187 Growth Clinic — Cuestionario previo a la consulta',
    stepOf: (n, t) => `Paso ${n} de ${t}`,
    next: 'Siguiente',
    prev: 'Atrás',
    submit: 'Enviar',
    submitting: 'Enviando...',
    doneTitle: 'Gracias',
    doneBody: 'Hemos recibido su cuestionario. Nos pondremos en contacto pronto.',
    retry: 'Reintentar',
    required: 'Este campo es obligatorio',
    invalidBirth: 'Por favor, introduzca una fecha de nacimiento válida.',
    submitError: 'Ocurrió un problema al enviar. Revise los datos e inténtelo de nuevo.',
    s1Title: 'Información básica',
    s2Title: 'Historial de crecimiento',
    s3Title: 'Familia e interés',
    s4Title: 'Salud y desarrollo',
    s5Title: 'Causas de la baja estatura',
    s6Title: 'Adjuntar archivos de exámenes',
    name: 'Nombre completo',
    nameEn: 'Nombre (en inglés)',
    gender: 'Sexo',
    male: 'Niño',
    female: 'Niña',
    birth: 'Fecha de nacimiento',
    year: 'Año',
    month: 'Mes',
    day: 'Día',
    country: 'País de residencia',
    countrySearch: 'Buscar país',
    countryEmpty: 'Sin resultados',
    growthRef: 'País de referencia de crecimiento',
    growthRefHint: '¿Con los niños de qué país comparamos? Normalmente el mismo donde vive.',
    fatherH: 'Estatura del padre (cm)',
    motherH: 'Estatura de la madre (cm)',
    desiredH: 'Estatura deseada (cm)',
    currentH: 'Estatura actual (cm)',
    currentW: 'Peso actual (kg)',
    grade: 'Grado escolar',
    classRank: 'Puesto de estatura en clase',
    phone: 'Teléfono',
    email: 'Correo electrónico',
    address: 'Dirección',
    gestWeeks: 'Semanas de gestación al nacer',
    birthWeight: 'Peso al nacer (kg)',
    birthNote: 'Algo destacable al nacer',
    growthHint: 'Complete con base en el registro escolar de salud o el historial pediátrico.',
    ageCol: 'Edad (grado)',
    heightCol: 'Estatura (cm)',
    yearlyGrowth: 'Estatura ganada en el último año (cm)',
    flagRapid: 'Ha crecido inusualmente rápido últimamente',
    flagSlowed: 'La velocidad de crecimiento se ha reducido notablemente',
    flagPuberty: 'Preocupa una pubertad precoz',
    yes: 'Sí',
    no: 'No',
    pastConsult: '¿El niño ha consultado antes en una clínica de crecimiento?',
    parentsInterested: '¿Ambos padres están interesados en el manejo del crecimiento?',
    sportsAthlete: '¿El niño es deportista o miembro de un equipo deportivo?',
    sportsEvent: 'Deporte',
    childInterested: '¿El niño está personalmente motivado por crecer?',
    acquisitionChannel: '¿Cómo nos conoció?',
    acquisitionChannelOpts: [
      { value: 'google', label: 'Búsqueda en Google' },
      { value: 'instagram', label: 'Instagram' },
      { value: 'facebook', label: 'Facebook' },
      { value: 'youtube', label: 'YouTube' },
      { value: 'referral', label: 'Recomendación de conocidos' },
      { value: 'ai', label: 'IA (ChatGPT, etc.)' },
      { value: 'other', label: 'Otro' },
    ],
    sLifeTitle: 'Hábitos de vida',
    sleepTime: 'Hora de acostarse',
    wakeTime: 'Hora de levantarse',
    exerciseFreq: 'Frecuencia de ejercicio',
    exerciseOpts: [
      { value: 'none', label: 'Casi nunca' },
      { value: 'week1_2', label: '1–2 veces por semana' },
      { value: 'week3_4', label: '3–4 veces por semana' },
      { value: 'daily', label: 'Todos los días' },
    ],
    milkDaily: 'Consumo de leche / lácteos',
    milkOpts: [
      { value: 'none', label: 'Casi nunca' },
      { value: 'sometimes', label: 'A veces (2–3 veces por semana)' },
      { value: 'daily1', label: '1 vaso al día' },
      { value: 'daily2plus', label: '2 o más vasos al día' },
    ],
    mealReg: 'Regularidad de las comidas',
    mealOpts: [
      { value: 'irregular', label: 'Irregular' },
      { value: 'mostly_regular', label: 'Bastante regular' },
      { value: 'very_regular', label: 'Muy regular' },
    ],
    chronic: 'Indique cualquier enfermedad actual o pasada en tratamiento.',
    tanner: 'Etapa de pubertad (etapa de Tanner)',
    tannerOpts: [
      'Etapa 1 — Aún sin signos de pubertad',
      'Etapa 2 — La pubertad apenas comienza',
      'Etapa 3 — Cambios notables en curso',
      'Etapa 4 — Pubertad casi completa',
      'Etapa 5 — Pubertad completa, cuerpo adulto',
    ],
    currentMeds: 'Medicamentos / suplementos actuales',
    voiceChange: 'Cambio de voz',
    voiceOpts: [
      { value: 'none', label: 'Aún no' },
      { value: 'started', label: 'Ha comenzado' },
      { value: 'done', label: 'Completado' },
    ],
    facialHair: 'Vello facial / corporal',
    facialOpts: [
      { value: 'none', label: 'Ninguno' },
      { value: 'fuzz', label: 'Vello fino' },
      { value: 'clear', label: 'Claramente visible' },
    ],
    menarche: 'Primera menstruación',
    menarcheOpts: [
      { value: 'none', label: 'Aún no' },
      { value: 'recent6m', label: 'Comenzó (en los últimos 6 meses)' },
      { value: 'over1y', label: 'Hace más de 1 año' },
    ],
    breastDev: 'Desarrollo mamario',
    breastOpts: [
      { value: 'none', label: 'Sin desarrollo' },
      { value: 'budding', label: 'Inicio (botón mamario)' },
      { value: 'clear', label: 'Desarrollo evidente' },
    ],
    causes: 'Posibles causas de la baja estatura (marque todas las que apliquen)',
    causeOpts: [
      { value: 'parents_short', label: 'Los padres son de baja estatura' },
      { value: 'parents_height_gap', label: 'Más bajo de lo esperado según la estatura de los padres' },
      { value: 'picky_eating', label: 'Alimentación selectiva / insuficiente' },
      { value: 'parents_early_stop', label: 'Un padre dejó de crecer temprano' },
      { value: 'insufficient_sleep', label: 'Sueño insuficiente' },
      { value: 'chronic_illness', label: 'Enfermedad crónica' },
    ],
    causesOther: 'Otras causas',
    additionalNotes: 'Notas adicionales (dudas o información relevante)',
    xrayUpload: 'Adjuntar archivo de radiografía',
    labUpload: 'Adjuntar resultados de laboratorio',
    uploadHint: 'Adjunte una imagen o un archivo PDF (opcional).',
  },

  // 아랍어(MSA, 격식). 숫자는 서양식 숫자 — 입력 칸이 서양식이라 표기를 맞춘다.
  ar: {
    pageTitle: 'عيادة 187 للنمو — استبيان ما قبل الزيارة',
    stepOf: (n, t) => `الخطوة ${n} من ${t}`,
    next: 'التالي',
    prev: 'رجوع',
    submit: 'إرسال',
    submitting: 'جارٍ الإرسال...',
    doneTitle: 'شكرًا لك',
    doneBody: 'تم استلام الاستبيان. سنتواصل معك قريبًا.',
    retry: 'حاول مرة أخرى',
    required: 'هذا الحقل مطلوب',
    invalidBirth: 'يرجى إدخال تاريخ ميلاد صحيح.',
    submitError: 'حدث خطأ أثناء الإرسال. يرجى مراجعة البيانات والمحاولة مرة أخرى.',
    s1Title: 'المعلومات الأساسية',
    s2Title: 'سجل النمو',
    s3Title: 'الأسرة والاهتمام',
    s4Title: 'الحالة الطبية والتطور',
    s5Title: 'أسباب قصر القامة',
    s6Title: 'إرفاق ملفات الفحوصات',
    name: 'الاسم الكامل',
    nameEn: 'الاسم (بالإنجليزية)',
    gender: 'الجنس',
    male: 'ذكر',
    female: 'أنثى',
    birth: 'تاريخ الميلاد',
    year: 'السنة',
    month: 'الشهر',
    day: 'اليوم',
    country: 'بلد الإقامة',
    countrySearch: 'ابحث عن الدولة',
    countryEmpty: 'لا توجد نتائج',
    growthRef: 'الدولة المرجعية لمعايير النمو',
    growthRefHint: 'بأطفال أي دولة نقارن طفلك؟ عادةً نفس بلد الإقامة.',
    fatherH: 'طول الأب (سم)',
    motherH: 'طول الأم (سم)',
    desiredH: 'الطول المرغوب (سم)',
    currentH: 'الطول الحالي (سم)',
    currentW: 'الوزن الحالي (كجم)',
    grade: 'الصف الدراسي',
    classRank: 'ترتيب الطول في الصف',
    phone: 'رقم الهاتف',
    email: 'البريد الإلكتروني',
    address: 'العنوان',
    gestWeeks: 'عمر الحمل عند الولادة (أسابيع)',
    birthWeight: 'الوزن عند الولادة (كجم)',
    birthNote: 'أي ملاحظات عند الولادة',
    growthHint: 'يرجى التعبئة من سجلات الصحة المدرسية أو السجل الطبي للطفل.',
    ageCol: 'العمر (الصف)',
    heightCol: 'الطول (سم)',
    yearlyGrowth: 'الزيادة في الطول خلال السنة الماضية (سم)',
    flagRapid: 'نما بسرعة غير معتادة مؤخرًا',
    flagSlowed: 'تباطأ معدل النمو بشكل ملحوظ مؤخرًا',
    flagPuberty: 'قلق بشأن البلوغ المبكر',
    yes: 'نعم',
    no: 'لا',
    pastConsult: 'هل سبق أن راجع الطفل عيادة نمو من قبل؟',
    parentsInterested: 'هل الوالدان مهتمان بمتابعة النمو؟',
    sportsAthlete: 'هل الطفل عضو في فريق رياضي أو لاعب تنافسي؟',
    sportsEvent: 'الرياضة',
    childInterested: 'هل لدى الطفل رغبة شخصية في زيادة طوله؟',
    acquisitionChannel: 'كيف سمعت عنا؟',
    acquisitionChannelOpts: [
      { value: 'google', label: 'بحث جوجل' },
      { value: 'instagram', label: 'إنستغرام' },
      { value: 'facebook', label: 'فيسبوك' },
      { value: 'youtube', label: 'يوتيوب' },
      { value: 'referral', label: 'توصية من صديق أو قريب' },
      { value: 'ai', label: 'الذكاء الاصطناعي (ChatGPT وغيره)' },
      { value: 'other', label: 'أخرى' },
    ],
    sLifeTitle: 'نمط الحياة',
    sleepTime: 'موعد النوم',
    wakeTime: 'موعد الاستيقاظ',
    exerciseFreq: 'عدد مرات ممارسة الرياضة',
    exerciseOpts: [
      { value: 'none', label: 'نادرًا' },
      { value: 'week1_2', label: 'مرة إلى مرتين أسبوعيًا' },
      { value: 'week3_4', label: '3 إلى 4 مرات أسبوعيًا' },
      { value: 'daily', label: 'يوميًا' },
    ],
    milkDaily: 'تناول الحليب ومنتجات الألبان',
    milkOpts: [
      { value: 'none', label: 'نادرًا' },
      { value: 'sometimes', label: 'أحيانًا (2–3 مرات أسبوعيًا)' },
      { value: 'daily1', label: 'كوب واحد يوميًا' },
      { value: 'daily2plus', label: 'كوبان أو أكثر يوميًا' },
    ],
    mealReg: 'انتظام الوجبات',
    mealOpts: [
      { value: 'irregular', label: 'غير منتظمة' },
      { value: 'mostly_regular', label: 'منتظمة في الغالب' },
      { value: 'very_regular', label: 'منتظمة جدًا' },
    ],
    chronic: 'يرجى ذكر أي حالات صحية حالية أو سابقة يخضع لعلاجها.',
    tanner: 'مرحلة البلوغ (مقياس تانر)',
    tannerOpts: [
      'المرحلة 1 — لا توجد علامات بلوغ بعد',
      'المرحلة 2 — بداية البلوغ',
      'المرحلة 3 — تغيّرات واضحة جارية',
      'المرحلة 4 — البلوغ شبه مكتمل',
      'المرحلة 5 — اكتمل البلوغ، جسم بالغ',
    ],
    currentMeds: 'الأدوية أو المكمّلات الحالية',
    voiceChange: 'تغيّر الصوت (خشونة الصوت)',
    voiceOpts: [
      { value: 'none', label: 'لم يبدأ بعد' },
      { value: 'started', label: 'بدأ' },
      { value: 'done', label: 'اكتمل' },
    ],
    facialHair: 'شعر الوجه والجسم',
    facialOpts: [
      { value: 'none', label: 'لا يوجد' },
      { value: 'fuzz', label: 'زغب خفيف' },
      { value: 'clear', label: 'ظاهر بوضوح' },
    ],
    menarche: 'أول دورة شهرية',
    menarcheOpts: [
      { value: 'none', label: 'لم تبدأ بعد' },
      { value: 'recent6m', label: 'بدأت (خلال الأشهر الستة الماضية)' },
      { value: 'over1y', label: 'مضى عليها أكثر من سنة' },
    ],
    breastDev: 'نمو الثدي',
    breastOpts: [
      { value: 'none', label: 'لم يبدأ' },
      { value: 'budding', label: 'بداية النمو' },
      { value: 'clear', label: 'نمو واضح' },
    ],
    causes: 'الأسباب المحتملة لقصر القامة (اختر كل ما ينطبق)',
    causeOpts: [
      { value: 'parents_short', label: 'الوالدان قصيرا القامة' },
      { value: 'parents_height_gap', label: 'أقصر مما هو متوقع من طول الوالدين' },
      { value: 'picky_eating', label: 'انتقائية في الطعام أو قلة تناول الطعام' },
      { value: 'parents_early_stop', label: 'توقف نمو أحد الوالدين مبكرًا' },
      { value: 'insufficient_sleep', label: 'عدم كفاية النوم' },
      { value: 'chronic_illness', label: 'مرض مزمن' },
    ],
    causesOther: 'أسباب أخرى',
    additionalNotes: 'ملاحظات إضافية (أسئلة أو أي شيء آخر)',
    xrayUpload: 'إرفاق صورة الأشعة',
    labUpload: 'إرفاق نتائج التحاليل',
    uploadHint: 'يرجى إرفاق صورة أو ملف PDF (اختياري).',
  },
};

export const ACQUISITION_KO: Record<string, string> = {
  google: '구글 검색',
  naver: '네이버 검색',
  instagram: '인스타그램',
  facebook: '페이스북',
  youtube: '유튜브',
  referral: '지인 소개',
  ai: 'ChatGPT 등 AI',
  other: '기타',
};

/** 어드민 표시용: 셀렉트 코드값 → 한국어 라벨 (미등록 코드는 원문 그대로) */
export function optLabelKo(
  opts: { value: string; label: string }[],
  value: string | null | undefined,
): string {
  if (!value) return '—';
  return opts.find((o) => o.value === value)?.label ?? value;
}

export function getLabels(lang: IntakeLang): IntakeLabelSet {
  return INTAKE_LABELS[lang];
}
