// Patient story — narrative biographical sketch generated by Gemini
// (cases/generate_patient_stories.mjs) or Claude manual fallback.
// Table: patient_stories (migration 013).

import { supabase } from '@/shared/lib/supabase';
import { logger } from '@/shared/lib/logger';

export interface PatientStory {
  id: string;
  child_id: string;
  title: string;
  story: string;
  model: string;
  source: 'gemini' | 'claude' | 'manual';
  generated_at: string;
  updated_at: string;
}

/** Returns Map<child_id, true> for every child that already has a cached story. */
export async function fetchStoryChildIds(): Promise<Set<string>> {
  const ids = new Set<string>();
  const PAGE = 1000;
  for (let from = 0; ; from += PAGE) {
    const { data, error } = await supabase
      .from('patient_stories')
      .select('child_id')
      .range(from, from + PAGE - 1);
    if (error) {
      logger.error('fetchStoryChildIds failed:', error);
      return ids;
    }
    if (!data || data.length === 0) break;
    for (const r of data as Array<{ child_id: string }>) ids.add(r.child_id);
    if (data.length < PAGE) break;
  }
  return ids;
}

export async function fetchStoryByChild(childId: string): Promise<PatientStory | null> {
  const { data, error } = await supabase
    .from('patient_stories')
    .select('*')
    .eq('child_id', childId)
    .maybeSingle();
  if (error) {
    logger.error('fetchStoryByChild failed:', error);
    throw error;
  }
  return (data as PatientStory | null) ?? null;
}
