// 재배포 릴스 영어판 보라 프레임 2단 헤더. youtubeId → { kicker, title }.
// 상단만 영어. 하단 자막은 EN + 中(간체) (STT 번역, 별도 데이터).
// 화자 = 남성 의사, professional 톤. draft 제작(2026-07-13).
import type { PurpleTitle } from "./purpleTitles";

export const PURPLE_TITLES_EN: Record<string, PurpleTitle> = {
  "9zW9kxeXZ9I": { kicker: "Especially photogenic", title: "Male stars' real heights" },
  "MeTgH1QF-pw": { kicker: "170cm is the new normal", title: "5th-gen girl group heights" },
  keuqhCyihmA: { kicker: "170cm is the new normal", title: "4th-gen girl group heights" },
  GZt5vF8uEug: { kicker: "Parents often believe", title: "5 growth myths that backfire" },
  IVeltl46vAU: { kicker: "Miss this window", title: "and lose 7cm" },
  a6xNHADHhBM: { kicker: "Why today's girl groups", title: "are so tall" },
  sWhRMSfN9Fk: { kicker: "195cm Haaland's", title: "one obsession" },
  vbFWARxrupc: { kicker: "Broad-shouldered Sinyu", title: "did this as a kid" },
  N9z6jdNSsA8: { kicker: "Age 6 vs. puberty", title: "When's the real window?" },
  hV95l_XqHMM: { kicker: "Growth plate injury?", title: "3 signs to see a doctor" },
  B9y6RmYQtj8: { kicker: "A height hormone?", title: "It can stop growth instead" },
  "0Yrd0j4dYvo": { kicker: "+20cm in high school", title: "What Kim Yeon-koung ate" },
  bvyCCUc5miQ: { kicker: "Straighten bowlegs", title: "and unlock hidden height" },
  rh6GDHr3ydo: { kicker: "The world's first egen-man", title: "and the first surgery" },
  LXGI2XrPfOI: { kicker: "Hard to believe under 170cm", title: "10 commanding male singers" },
  VqH1H74YK9c: { kicker: "Same height now", title: "Why final heights differ" },
  "9C7PIn1Bub0": { kicker: "Fooled by their proportions", title: "10 actresses under 160cm" },
  cdseujz5pfI: { kicker: "Can racy content", title: "stunt a child's growth?" },
  YoDN1CB8cDw: { kicker: "During exams, we feed", title: "our kids this" },
  CkZRzI10P5I: { kicker: "Could it be your child?", title: "3 checks for false puberty" },
  ONrlbgzFr60: { kicker: "Grow just by sleeping", title: "Kim Tae-ri's sleep secret" },
  PKz1IHNcNaA: { kicker: "Growth plates closed?", title: "Did you check here too?" },
  oLaBCrOJCRw: { kicker: "Surprisingly bad for height", title: "4 kids' snacks" },
  TPQYGeSmNUE: { kicker: "In Korea, 1cm of height", title: "is worth how much?" },
  X_3SGOd3DzM: { kicker: "Kids who stopped growing", title: "all ate this" },
  "Pl-668v5LNU": { kicker: "Actor Lee Byung-hun", title: "Really 177cm?" },
  "0iDQcDBTKeg": { kicker: "Can toy slime", title: "harm growth plates?" },
  lU0doLYLms0: { kicker: "Calcium and vitamin D alone", title: "won't grow bones" },
  ZHY8Q9FpuMM: { kicker: "Before a growth clinic", title: "check these 5 things" },
  "-upHROr_K50": { kicker: "183cm by 9th grade", title: "Jung Si-a's growth diet" },
  "Pe98BaA-sJg": { kicker: "Your child", title: "How many cm per year?" },
  KHDXNSCLW4E: { kicker: "Why do a bone-age test", title: "in elementary school?" },
  LXm3mTuWp90: { kicker: "Taller than ever", title: "180cm 'perfect' boy idols" },
  Ifl_AkdDIbg: { kicker: "Want to be a model?", title: "The habit you need" },
  p3D9l27CCSE: { kicker: "Does formula boost height?", title: "The truth behind the rumor" },
  LDELkwun3S0: { kicker: "Feeding and sleep are fine", title: "but still not growing?" },
  gCni4ZRZM0k: { kicker: "Gorgeous but short", title: "10 male actors" },
  Jw1IG37_ugs: { kicker: "Wonyoung & Yujin's", title: "170cm secret—for real?" },
  "5f8sQ3x6Lgk": { kicker: "In 60 seconds", title: "Limb-lengthening surgery" },
  NUSYolfwBAA: { kicker: "Why does height", title: "change every measurement?" },
};
